# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68470a47939b14f37e80a201750dde919fdffcfe073f55c45f6a13938818409910e40780d63da6dc986a67c94dd1d4bfb7e9832808397b82f1b83d75485af86e

test:
  secret_key_base: b0a8a039f5c66597b6ad3e8aebb108c7893aae2f6e8702ea3781fff2aa238f5c5216f1f5c3985d6278cb08ec498f3a2ab95620cb7dd198bf64bf2db89ffa76b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
